### ISSUE TITLE
cmake fail

### ISSUE THREAD

**Issue by caginagirdemir** [whoenig/vicon-datastream-sdk#2]
Hello, 

![image](https://user-images.githubusercontent.com/50463214/154842385-731eb411-4bb6-42c5-856f-7906f08e6542.png)

I got this error. I am using Ubuntu(Windows Sub System). How can I rid of the error?

**Comment by whoenig** [comment]
Install boost, e.g., `sudo apt install libboost-all-dev`.

**Comment by caginagirdemir** [comment]
Thank you for your support.
