### ISSUE TITLE
How to compile a simple C program with DataStream SDK

### ISSUE THREAD

**Issue by caginagirdemir** [whoenig/vicon-datastream-sdk#3]
Hello again.

I have research many times but there is just a one source that is Documentation pdf. 
But I can't compile a simple program which use printf client_getversion. 
in Document file see include DataStreamClient.h and gcc with libViconDataStreamSDK_CPP.a

![image](https://user-images.githubusercontent.com/50463214/154849151-a1274ca4-1463-4119-a8b7-12eb537ef820.png)

so I wrote this shell command -> gcc main.c libViconDataStream_CPP.a

When I use ViconDataStreamSDK_CPP/DataStreamClient.h
I got errors like "vector: no such file or directory" or "memory: no such file or directory" or "string: no such file or directory"

![image](https://user-images.githubusercontent.com/50463214/154849679-878746f7-6995-4b87-bf8b-fa89c759551a.png)

Error: 

![image](https://user-images.githubusercontent.com/50463214/154849721-04a343b8-fde3-4cb8-949e-b51d5a9aafc4.png)

When I use ViconDataStreamSDK_C/CClient.h

![image](https://user-images.githubusercontent.com/50463214/154849592-928e7594-8e74-4cf9-969f-86c6d0f09c9f.png)

Error:
![image](https://user-images.githubusercontent.com/50463214/154849615-edba9ac8-f37d-4059-96ca-2c90e737a365.png)

I really stuck.  There is no video about it. There is no sample code.

**Comment by caginagirdemir** [comment]
I guess second error WSL Ubuntu fault. (undefined reference to ' ... '. Because I found same errors on internet.

**Comment by whoenig** [comment]
This repository is just a mirror. I can't provide support for the actual SDK. Note, however, that a C++ example application is included.
